### ISSUE TITLE
关于代码的一点疑惑

### ISSUE THREAD

**Issue by ShenMian** [JingYiJun/sfSnakePro#2]
代码写得非常漂亮, 看上去十分赏心悦目. 不过几点疑惑和建议:  
1. 多处看似应该使用局部变量的地方却使用了 `static` 进行修饰. 如:  
	https://github.com/JingYiJun/sfSnakePro/blob/13e1a23480d77b5bb82806705873c2a59ee5cd01/src/element/Snake.cpp#L95
2. 部分参数没有通过引用传递([C++ Core Guidelines F.16](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f16-for-in-parameters-pass-cheaply-copied-types-by-value-and-others-by-reference-to-const)). 如:  
	https://github.com/JingYiJun/sfSnakePro/blob/13e1a23480d77b5bb82806705873c2a59ee5cd01/src/element/Button.cpp#L11
3. 建议使用 [std::random_device](http://en.cppreference.com/w/cpp/numeric/random/random_device)
	https://github.com/JingYiJun/sfSnakePro/blob/13e1a23480d77b5bb82806705873c2a59ee5cd01/src/screen/GameScreen.cpp#L85

**Comment by JingYiJun** [comment]
谢谢你的建议。
1. 只是想避免每次都创建局部变量，可能对性能影响不大
2. 没有用引用是我的疏忽了。

**Comment by ShenMian** [comment]
没具体测试过, 但我猜把全部变量的生命周期都改为静态的可能会导致性能下降. 局部变量本身应该是几乎没有创建开销的. 但是生命周期变成静态的不知道是否会影响到 CPU cache 等其他东西.

**Comment by ShenMian** [comment]
谢谢的你回复, 我大概明白了.
